language: node_js
node_js:
  - "8.2.1"
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
jobs:
  include:
    - stage: CI CD For WSO2 API Cloud 
      install:
      - npm install newman
      script:
      - echo "Start deploying the managed REST API to WSO2 API Cloud Dev Tenant"
      - node_modules/.bin/newman run DeployAPI/WSO2_API_PUBLISHER.postman_collection.json -e DevEnvironment/Development.postman_environment.json --global-var username=$devclouduser --global-var password=$devclouduserpass --bail || travis_terminate 1;
      - echo "Start testing the REST API in WSO2 API Cloud Dev Tenant"
      - node_modules/.bin/newman run TestAPI/WSO2_API_STORE_TESTS.postman_collection.json -e DevEnvironment/Development.postman_environment.json --global-var username=$devclouduser --global-var password=$devclouduserpass --bail || travis_terminate 1;
      - echo "Promoting to Staging Environment" 
      - echo "Start deploying the managed REST API to WSO2 API Cloud Staging Tenant"
      - node_modules/.bin/newman run DeployAPI/WSO2_API_PUBLISHER.postman_collection.json -e StagingEnvironment/Staging.postman_environment.json --global-var username=$stagingclouduser --global-var password=$stagingclouduserpass --bail || travis_terminate 1;
      - echo "Start testing the REST API in WSO2 API Cloud Staging Tenant"
      - node_modules/.bin/newman run TestAPI/WSO2_API_STORE_TESTS.postman_collection.json -e StagingEnvironment/Staging.postman_environment.json --global-var username=$stagingclouduser --global-var password=$stagingclouduserpass --bail || travis_terminate 1;

